# Keys to use when saving/loading tensor/model files
X_KEY = "X_tensor"
Y_KEY = "y_tensor"
MAP_KEY = "label_map"
MODEL_STATE_KEY = "model_state"
F1_MACRO_KEY = "F1_macro"
N_EPOCHS_KEY = "n_epochs"
BEST_EPOCH_KEY = "best_epoch"
HIDDEN_SIZE_KEY = "hidden_size"
N_DIMS_KEY = "n_dims"
N_CLASSES_KEY = "n_classes"
LEARNING_RATE_KEY = "learning_rate"
OPTIMIZER_NAME_KEY = "optimizer_name"
LOSS_FN_NAME_KEY = "loss_function_name"
